### PR TITLE
Bom import xarray

### LINKED ISSUE #215: Implement importer for NWP (netcdf) data
Implement function to read in CF-compliant NetCDF data, not (yet) including interpolation to the radar / nowcasting grid. This might be simplified by moving to xarray first. Required for #212 .

### PR DESCRIPTION
**Pull request by cvelascof**
This PR reads directly BoM netCDF files using xarray and returns a DataArray.
Also it implements some tests for the new importer based on xarray.

### CODE REVIEW

**Comment by cvelascof** [comment]
This PR uses xarray to load the BoM netcdf files and adds the pySTEPS metadata as attributes to the DataArrays (Data and coordinates).
New routines were created and named as the old ones plus the postfix "_xr". Old routines are still in the repository for legacy purposes. All tests related with the new routines are passing.

Test failing are related with io_import_mrms_grib routine.
@dnerini . @RubenImhoff  can you give it a look and try to fix them?

**Comment by RubenImhoff** [comment]
The failing MRMS tests seems like something @aperezhortal knows.

**Comment by cvelascof** [comment]
hi @ladc ... good point ... _import_bom_rf3_geodata_xr already have varname as parameter but it would be nice to connect it with kwargs passed to the parent function import_bom_rf3_xr. I will do that soon.

On the other hand, importers.py is in theory only for radar inputs ... so probably we may need a new nwp_importers.py to collect the specific routines to read and preprocess nwp datasets. For example, deal with lat/lon rather than x and y, or transform accumulated precipitation from runtime that it is typical for NWP variable to accumulated precipitation for each time step that it is what actually will be blended with radar data.
 What do you think?

**Comment by cvelascof** [comment]
it seems chunks are not working in python3.6 for some reason but they work great using python3.8... so at this point I will not pass chunks information to xarray.
Something to think about later on.

**Comment by cvelascof** [comment]
@ladc  this adds an importer for some of the sample nwp data in pysteps-data. We may need to add this nwp reader to other branches. This is just the foundation for additional NWP data readers.

**Comment by ladc** [comment]
@cvelascof Great! I don't know how realistic it is to make a generic NWP importer function that can read CF-compliant netcdf files but this looks like a good start.

**Pull request merged**
