### PR TITLE
Add precip colorscale from blending manuscript

### PR DESCRIPTION
**Pull request by RubenImhoff**

### CODE REVIEW

**Comment by RubenImhoff** [comment]
pysteps colorscale:
image

STEPS-BE colorscale: 
image

BOM-RF3 colorscale:
image

New colorscale STEPS-NL:
image

**Comment by dnerini** [comment]
Real nice, Ruben! What about displaying the new colormap in one of the existing gallery examples? The steps blending maybe?

**Comment by RubenImhoff** [comment]
Sounds good, I'll do so!

**Review by dnerini — APPROVED** [review]
Thanks a lot, very nice addition to our rainfall palettes ;-)

**Comment by RubenImhoff** [comment]
I see that I'm not authorized (anymore?) to merge it - could you merge it, Daniele?

**Comment by dnerini** [comment]
uhm sorry, now you should be again be able to merge approved PRs into master!

**Pull request merged**
