### PR TITLE
Add compression and documentation options to netCDF exporter

### PR DESCRIPTION
**Pull request by RubenImhoff**
Improvement to netCDF exporter to add optional arguments scale, offset, fill_value and datatype for reduced storage possibilities. In addition, some kwargs are add to make it possible to add documentation or explanatory strings to the netCDF file.

### CODE REVIEW

**Comment by RubenImhoff** [comment]
The failed tests seem to be unrelated to the changes in this PR. It is related to opencv, it seems, does something go wrong with the installation of that in some of the python versions?

**Comment by dnerini** [comment]
@RubenImhoff just to understand, did you fork this from master or from #351 ?

**Comment by RubenImhoff** [comment]
This PR is forked from master, indeed (independent from #351)

**Comment by dnerini** [comment]
it should be fixed on master now, can you merge master into this branch @RubenImhoff to see if now tests pass?

**Comment by RubenImhoff** [comment]
Thanks, Daniele! I also added some tests, but couldn't find a way to assert if the passed new arguments also end up in the netCDF. If you know a way, let me know, otherwise this should be good as is.

**Review by dnerini — APPROVED** [review]
Many thanks for the great contribution!

**Pull request merged**
