### PR TITLE
Change license to BSD-3

### PR DESCRIPTION
**Pull request by dnerini**
* Addressing issue #56.
* Ideally, this should  get approval from all the pysteps contributors before merging.

### CODE REVIEW

**Comment by dnerini** [comment]
@RubenImhoff, @tjniemi, @pkars and @juhi24 

please do let us know if you have anything against this license change.

**Review by aperezhortal — APPROVED** [review]

**Comment by pkars** [comment]
I have no objections to this license change. 

In fact, I wholeheartedly agree with switching to BSD-3 license. That'll help out in avoiding licensing problems in the future, if (when) pysteps library is used in operational nowcasting systems.

**Comment by RubenImhoff** [comment]
Me neither, it's good to see that you've thought about this possible issue. I think that the BSD-3 license is what we're looking for within this platform and I totally agree with the arguments given in favour of the BSD-3 license.

**Comment by juhi24** [comment]
I don't have any objections either.

Just out of curiosity: Is the third clause useful? If someone puts a pySTEPS logo on their poster, does it violate the license? 

If the third clause is not needed, I would recommend the MIT license over BSD-2, since the former seems to be more widely known and used. At least I had to look up BSD licenses since I hadn't seen those for a while.

Then again, the differences are mostly cosmetic. I'm good with any BSD or MIT license.

**Comment by aperezhortal** [comment]
@juhi24 , the third clause applies only to the copyright holder or the names of the pysteps contributors. Since the logo doesn't mention that, my understanding is that using the logo in a poster does not violate the license.

**Comment by juhi24** [comment]
@aperezhortal, my point is that the third clause might prohibit some type of attribution that might be beneficial. Maybe. Can you think of any situation where this clause might be potentially useful? If not, BSD-2 or MIT would be preferable.

If you want to include the third clause, please mind the wording: As the license states, the contributors ARE the copyright owners. So I would change "Neither the name of the copyright holder nor the names of its contributors may be used..." to "Neither the name of PySteps nor the names of its contributors may be used..." or "The names of the PySteps contributors may not be used...".

Sorry for being such a nitpicker.

**Comment by aperezhortal** [comment]
@juhi24, no worries. Feel free to share your thoughts since discussions are encouraged in the PRs. 

> If you want to include the third clause, please mind the wording: As the license states, the contributors ARE the copyright owners. So I would change...

Changes in the licenses generally discouraged. The license, as it is, went through an approval process by the [Open Source Initiative]( https://opensource.org/approval), where it was revised word by word. 
Therefore, if you introduce a small change, it won't be a BSD-3 license anymore and, to for our license to be considered an official "open source license", you now need to submit it to the [Open Source Initiative]( https://opensource.org/approval) for approval.
[**Edit**: After some research, it seems that it is common to change the 3rd clause in this license to fit the project needs. Many of the projects that do this, they just don't use the "BSD-3 License" name.]

> Can you think of any situation where this clause might be potentially useful? If not, BSD-2 or MIT would be preferable. 

>"Neither the name of PySteps nor the names of its contributors may be used..." 

The 3 clause applies mostly to our names (and "Pysteps developers"). It does not apply to the PySTEPS name. This clause is protecting us, for example, from commercial applications using our names for promoting their software. This clause can become very useful if, for example, an important organization contributes to the software and they don't want their name being used to promote a product build using pysteps.

But, I understand your point. If you search in google or stackoverflow "MIT vs BSD", you will find many discussions similar this PR, with many good points on either side and no clear winner :S

**Comment by dnerini** [comment]
These are all very relevant considerations and now it is the right moment to discuss them.

I think @juhi24 makes a very valid point also when mentioning that MIT is more widely known compared to BSD. We should then consider whether the 3 clause in BSD is that important to us and, if not, perhaps consider using the more widely used MIT license.

**Comment by loforest** [comment]
Just a couple of links to help the "final" decision. Here are some statistics on percentage of license use:
https://resources.whitesourcesoftware.com/blog-whitesource/top-10-open-source-software-licenses-of-2016-and-key-trends
MIT 25% and BSD-3 only 6% (but more if also considering other clauses). So, if MIT has a serious problem, many more of us have one and will probably need to update our licenses again :-)

Here some additional thoughts:
https://exygy.com/which-license-should-i-use-mit-vs-apache-vs-gpl/
I like the conclusion based on what we fear the most:
- afraid of too few people using it? MIT.
- same as above but also afraid of people misusing the names of contributors or software? BSD-3.
- afraid of patent trolls? Apache 2.0. More wordy permissive license (as MIT or BSD) but designed for lawyers.
- afraid of people making money with it? GPL. 

Since several of us work in public weather services, we could also consider the license that is safer and simpler for our employer. Of course, this is not easy to predict in advance as the open-source world (and licenses) is evolving rapidly.

**Comment by cvelascof** [comment]
Interesting discussion. 
To add some information about last comment of @loforest (https://github.com/pySTEPS/pysteps/pull/67#issuecomment-476897891), UK MetOffice publishes under the LGPLv3 licence its free and open source projects, Iris and Cartopy (https://scitools.org.uk/organisation.html#organisation-top).
More info on LGPLv3.0 here, https://choosealicense.com/licenses/lgpl-3.0/ and here (https://www.gnu.org/licenses/lgpl.html)

Said that I would prefer to use a short text license rather than a large complex text license, and also a license that states in clear text, warranty and liability limitations. 

I would be happy using BSD-3.

**Comment by wcwoo** [comment]
As a potential user/collaborator, I'll be happy with either MIT or BSD-3.  Many thanks!

**Comment by juhi24** [comment]
Thanks @aperezhortal and others for explaining use cases for the 3rd clause. Sounds reasonable. BSD-3 could indeed be the better option here. I'm still happy with either BSD and MIT options as well as LGPLv3 as mentioned by @cvelascof.

**Review by pulkkins — APPROVED** [review]

**Review by loforest — APPROVED** [review]

**Comment by dnerini** [comment]
Thank you all for your inputs and the nice discussion!
From what I gathered, all of us agree with the change towards the BSD-3 license.
I propose to close here the discussion and merge the pull request.

**Pull request merged**
