### PR TITLE
Initial file for RainFARM

### PR DESCRIPTION
**Pull request by jleinonen**
Added initial file for RainFARM downscaling method, to be modified for compatibility with PySTEPS.

### CODE REVIEW

**Comment by aperezhortal** [comment]
Hi @jleinonen, welcome to pysteps, and thanks for the contribution! 

One question, is this PR work in progress? Or it is ready for review?

**Comment by jleinonen** [comment]
Hi @aperezhortal, I submitted this PR on request by @dnerini - he can decide what to do with it.

**Comment by aperezhortal** [comment]
Great! I was just double-checking before starting the review.

**Comment by dnerini** [comment]
Correct, I  asked @jleinonen to push his code.to this branch to start a new downscaling module. I'll be working on integrating it better in the package.

**Pull request merged**
