### PR TITLE
Bugfix reproducibility & ensemble member order with dask

### PR DESCRIPTION
**Pull request by mpvginde**
This PR (hopefully) fixes 2 issues:
#337: Strange artifacts showing up in the STEPS nowcasting due to the random order of the ensemble members in the numpy array when using dask multi-threading

#346: No reproducibility  of the (blended) STEPS nowcast results even when a fixed seed argument is given

### CODE REVIEW

**Comment by dnerini** [comment]
Nice job @mpvginde! This looks fantastic and I'm curious to hear from @RubenImhoff about #337.

I was wondering, should we add an explicit test on reproducibility?

**Comment by RubenImhoff** [comment]
Great work, @mpvginde! I will have a look at the PR later this week. :)

**Review by RubenImhoff — COMMENTED** [review]
Hi @mpvginde, great work! This indeed solves the issue. I know that the same issues occurs when using the LINDA nowcasting model. Would a similar fix work there, too?

**Comment by dnerini** [comment]
Hi @mpvginde should we try to push your fixes quickly to master and release them? Do you need any support of the issues that are still open or you think this is now ready to be merged?

**Comment by mpvginde** [comment]
Hi @dnerini, 
I noticed last week that in some cases, the result was also dependent on the number of dask workers used.
This should be fixed now with the last commit that I added.
I think this can be merged now.
I'm not sure why the Black check is failing though, If somebody could help me with that.

I did notice that the method used for generating the random numbers is using some deprecated numpy-functions.
If I find some more time I will try to update the generation of random number to the latest best practices.
But for now this fix should be ok.

**Comment by dnerini** [comment]
> I think this can be merged now.

Brilliant! Just wondering if we should include the fix for the `linda` method too, as mentioned by @RubenImhoff?

> I'm not sure why the Black check is failing though, If somebody could help me with that.

maybe you're using a older version of black locally? during tests we are using the latest available version

**Comment by dnerini** [comment]
alright, I'm merging this, thanks a lot @mpvginde for the nice contribution!

**Pull request merged**
