### PR TITLE
support for xarray

### PR DESCRIPTION
**Pull request by dnerini**
A simple attempt to at least partially address #12 by providing some sort of support to xarray within pysteps.

- define xarray as optional dependency
- support xarray format within (some/few) pysteps methods
- provide tutorial on the use of xarray with pysteps
- anything else?

the example tutorial is based on the [gist](https://gist.github.com/kmuehlbauer/645e42a53b30752230c08c20a9c964f9) from @kmuehlbauer.

doc: https://pysteps.readthedocs.io/en/support_xarray/
tutorial: https://pysteps.readthedocs.io/en/support_xarray/auto_examples/xarray_pysteps.html#sphx-glr-auto-examples-xarray-pysteps-py

### CODE REVIEW

**Comment by wcwoo** [comment]
Just noticed that you are adding xarray support to pySTEPS.  Many thanks!

We've written some wrappers in the development version of SwirlsPy, so that users will be able to call pySTEPS's methods in addition to SWIRLS's original ROVER + SLA.  An example and a documentation are as follows:
* https://docs.com-swirls.org/dev/auto_examples/steps_hk.html#sphx-glr-auto-examples-steps-hk-py
* https://docs.com-swirls.org/dev/swirlspy.qpf.fc.html

If you wish, you may reference our codes, though there are some differences in the design philosophy, e.g. SwirlsPy advects reflectivity while pySTEPS advects rainfall rate.  Please also feel free to let me know if you would us to contribute to pySTEPS.

By the way, I am looking to launch the development version this month, and feel a need to acknowledge pySTEPS along with other projects. e.g. wradlib, CartoPy etc.  I am thinking of adding a page dubbed "Acknowledgement", but do you and your team have any preference on how best to be acknowledged?

**Comment by dnerini** [comment]
Hi @wcwoo ! Thanks for your comment, see below for my responses.
 
> 
> Just noticed that you are adding xarray support to pySTEPS. Many thanks!

Yes, it is a first attempt and still very much work in progress, but we hope to get something up and running soon!

> We've written some wrappers in the development version of SwirlsPy, so that users will be able to call pySTEPS's methods in addition to SWIRLS's original ROVER + SLA. An example and a documentation are as follows:
> 
>     * https://docs.com-swirls.org/dev/auto_examples/steps_hk.html#sphx-glr-auto-examples-steps-hk-py
> 
>     * https://docs.com-swirls.org/dev/swirlspy.qpf.fc.html
> 

I'm happy to see that you managed to integrate pysteps into your own application! 
Please let us know about your experiences, we are very keen on getting some feedback.
I will certainly take a closer look at your examples and code, thanks! 

> 
> If you wish, you may reference our codes, though there are some differences in the design philosophy, e.g. SwirlsPy advects reflectivity while pySTEPS advects rainfall rate. Please also feel free to let me know if you would us to contribute to pySTEPS.
> 

Side note: the advection (and optical flow) routines in pysteps do _not_ require rainfall rates or any other specific unit/transformation. We typically recommend to transform the rain rates to better approximate a symmetric distribution, which is required by some of the statistical methods we use, particularly in the STEPS method. 

We welcome contributions of any kind! This can include correcting and improving existing modules based on your experience, but also implementing new modules, as for example the ROVER optical flow. If you wish to discuss further this topic we can open a new issue or discuss it on our Slack channel (I just sent you the invitation to join it).

> By the way, I am looking to launch the development version this month, and feel a need to acknowledge pySTEPS along with other projects. e.g. wradlib, CartoPy etc. I am thinking of adding a page dubbed "Acknowledgement", but do you and your team have any preference on how best to be acknowledged?

Excellent news! Personally, I don't have a strong opinion about the best way to acknowledge us. If possible, it would be nice to include the reference to our github page and to our reference GMD publication.

**Comment by wcwoo** [comment]
> Side note: the advection (and optical flow) routines in pysteps do _not_ require rainfall rates or any other specific unit/transformation. We typically recommend to transform the rain rates to better approximate a symmetric distribution, which is required by some of the statistical methods we use, particularly in the STEPS method.

I see.  It is not really a problem as we just converted reflectivity to rainfall rate, passed the data to STEPS, and converted the outputs back to reflectivity.  The reason we keep using reflectivity instead of rainfall rate is that our aviation forecasting divisions have applications that depend on whether the forecast (equivalent) reflectivity would be exceeded.  

> We welcome contributions of any kind! This can include correcting and improving existing modules based on your experience, but also implementing new modules, as for example the ROVER optical flow. If you wish to discuss further this topic we can open a new issue or discuss it on our Slack channel (I just sent you the invitation to join it).

I can imagine that we could contribute the wrappers for pySTEPS in Com-SWIRLS back to pySTEPS, but I need to scrutinize the codes and think about the workflow first.  By the way, my programmer @SelokYeung helped with the integration of pySTEPS into Com-SWIRLS.

> Excellent news! Personally, I don't have a strong opinion about the best way to acknowledge us. If possible, it would be nice to include the reference to our github page and to our reference GMD publication.

Thanks for your advice.  I will include the references accordingly.

**Comment by dnerini** [comment]
Unfortunately this PR got a bit neglected and lagged behind master. I close it without merging, the idea being to soon open a new one.

**Pull request closed without merging**
