### PR TITLE
Load pysteps-data

### PR DESCRIPTION
**Pull request by dnerini**
* Address #70 
* Follow the same wradlib approach
* Git clone the pysteps-data repository with Travis
* Export the path to the data as PYSTEPS_DATA
* Add utility function to read the PYSTEPS_DATA path
* Update the existing io test routines where necessary
* Remove the sample data

### CODE REVIEW

**Comment by dnerini** [comment]
We still need to implement the same approach when building the sphinx-gallery with Read the Docs.

**Comment by dnerini** [comment]
I also wonder whether we could better integrate this approach within the pystepsrc file, by directly setting all the "root_path" variables there after cloning the pysteps-data repository. 
What do you think, @aperezhortal ?

**Comment by aperezhortal** [comment]
@dnerini I like the idea. I pushed an implementation of what you propose. The travis.py script reads the default pystepsrc file, update the root_path, and create the pystepsrc.travis file. Then, on travis, the PYSTEPSRC is set with the full path to the new rc file. Maybe it needs more test, but if it work well, when pysteps is loaded it fetch the configuration from the new rc file.

**Comment by dnerini** [comment]
@aperezhortal This looks great!

It works very nicely with Travis:
``` 
python -c "import pysteps as stp;"
Pysteps configuration file found at: /home/travis/build/pySTEPS/pysteps/pystepsrc.travis
```
And also the test of the bom importer went through!

I will therefore remove the other method to avoid clutter in the library.

Edit: I moved travis.py to scripts/travis.py, since I'll have to create a similar scripts for Read the Docs, too

**Pull request merged**
