### PR TITLE
Add more details for minimum python version

### PR DESCRIPTION
**Pull request by Fangyh09**
Python3.6 is the minimum python version to support F-string, which needs attention. 
I tried to use python3.5 and failed very late. It will save time to reinstall python3.6 at the beginning.

### CODE REVIEW

**Comment by aperezhortal** [comment]
Hi @Fangyh09, thanks for the PR. The minimum python version was already specified in the documentation. 

> Python3.6 is the minimum python version to support F-string, which needs attention.

Although the f-strings supported by python 3.6 is one of the main reasons why that version is needed, there are other functionalities that can be used during the development of the library  (see https://www.python.org/downloads/release/python-360/).

> I tried to use python3.5 and failed very late. It will save time to reinstall python3.6 at the beginning.

You are right, it will be better if we make clear the python version needed if you are installing from sources or using pip.

I suggest the following suggested changes:

line 11 as it was originally:
* `python >=3.6 <http://www.python.org/>`_

line 91 to:
**IMPORTANT**: installing from source requires python=>=3.6 and numpy already installed.

line 138:
**IMPORTANT**: the installation using pip requires python=>=3.6 already installed.

Sorry for suggesting the changes in the old way. Github does not allow suggestions on not modified  lines.

**Comment by aperezhortal** [comment]
@Fangyh09, no need to close the PR. Y If you want, you can push new commits to your branch (patch-1) with the suggested modifications and then we can merge the PR.

**Comment by Fangyh09** [comment]
Okay~

**Comment by dnerini** [comment]
any update on this pull request, @Fangyh09 ?

**Comment by Fangyh09** [comment]
Nope

**Comment by dnerini** [comment]
:-)
Right, I'll close it for the time being, if you agree.
Feel free to reopen it in case you decide to include @aperezhortal 's suggestions.

**Pull request closed without merging**
