### PR TITLE
Add Z-R parameters (#103)

### PR DESCRIPTION
**Pull request by dnerini**
Include `zr_a` and `zr_b` parameters in the metadata where available.

TO DO:
- @pulkkins can you take care of the FMI importers (since the data are stored as reflectivities)?
- @cvelascof can you double-check with the BOM data?
- @RubenImhoff is the information available for the KNMI composite?
- OPERA importer

**Under development, please do not merge.**

### CODE REVIEW

**Comment by RubenImhoff** [comment]
Thanks, Daniele, looks good! I'll add the parameters of the KNMI data tomorrow (they're not in the metadata of the hdf5 files).

**Review by RubenImhoff — APPROVED** [review]

**Review by pulkkins — APPROVED** [review]

**Comment by RubenImhoff** [comment]
I have updated the KNMI importer to also allow for 2D reflectivity fields. The zr_a and zr_b parameters are included now. 

@ Daniele and Seppo, I accidentally uploaded an older version of importers.py and adjusted my mistake the commit after. So it looks like I changed a lot, but that's mostly Daniele's work that's back in the code now. Could you check the changed KNMI functionality?

**Comment by dnerini** [comment]
Thanks @RubenImhoff for your help! I have noticed that you removed all the blank lines in the docstrings, was this intentional? I reintroduced them for the moment. I have also slightly edited your KNMI importer's docstrings, hope this is OK with you.

The z-r parameters for the OPERA and BoM importers are still missing, while for the other importers these have been hardcoded (which is not ideal). I'm anyway merging this PR at its current status, hoping to do the remaining work at some point in the future.

**Comment by RubenImhoff** [comment]
Thanks, @dnerini! Removing the blank lines was not intentional indeed, thanks for the update, looks good!

**Pull request merged**
